name: CI
on: push
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: Run unit tests
      run: make test

    - name: Run checkmake on Makefile
      run: |
        make
        ./checkmake Makefile

  docker:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/mrtazz/checkmake/checkmake:${GITHUB_SHA}

    - name: push the docker image to GPR
      if: github.ref == 'refs/heads/master'
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u mrtazz --password-stdin
        docker push docker.pkg.github.com/mrtazz/checkmake/checkmake:${GITHUB_SHA}
        docker logout docker.pkg.github.com

    - name: push the docker image to docker hub
      if: github.ref == 'refs/heads/master'
      run: |
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login hub.docker.com -u mrtazz --password-stdin
        docker push mrtazz/checkmake:${GITHUB_SHA}
        docker logout hub.docker.com
